org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
org.gradle.parallel=true
org.gradle.workers.max=4
# 工程在「星海/省海渔…」中文路径下，不关这个 AGP 会直接停
android.overridePathCheck=true


# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
